services:
  - type: web
    name: chalk-and-choice
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=$PORT app:app
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: CLASSVOTE_DB
        value: /var/data/classvote.db
